# Generated by Django 4.1.2 on 2022-11-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
