# Generated by Django 4.1.2 on 2022-11-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
